import frappe

def execute():
	custom_fields = [
		{'doctype': 'Supplier Quotation', 'fieldname': 'license'},
		{'doctype': 'Payment Schedule', 'fieldname': 'is_billed'},
		{'doctype': 'Payment Schedule', 'fieldname': 'cb_schedule'},
		{'doctype': 'Item', 'fieldname': 'hub_sync_id'},
		{'doctype': 'Item', 'fieldname': 'enable_metrc'},
		{'doctype': 'Item', 'fieldname': 'sb_metrc'},
		{'doctype': 'Item', 'fieldname': 'metrc_id'},
		{'doctype': 'Item', 'fieldname': 'metrc_item_category'},
		{'doctype': 'Item', 'fieldname': 'metrc_unit_value'},
		{'doctype': 'Item', 'fieldname': 'cb_metrc'},
		{'doctype': 'Item', 'fieldname': 'metrc_uom'},
		{'doctype': 'Item', 'fieldname': 'metrc_unit_uom'},
		{'doctype': 'Item', 'fieldname': 'bloomtrace_id'},
		{'doctype': 'Contract', 'fieldname': 'sb_signature'},
		{'doctype': 'Contract', 'fieldname': 'project_template'},
		{'doctype': 'Contract', 'fieldname': 'customer_signature'},
		{'doctype': 'Contract', 'fieldname': 'project'},
		{'doctype': 'Contract', 'fieldname': 'contract_terms_display'},
		{'doctype': 'Contract', 'fieldname': 'contract_terms_help'},
		{'doctype': 'Contract', 'fieldname': 'employee_name'},
		{'doctype': 'Contract', 'fieldname': 'company'},
		{'doctype': 'Contract', 'fieldname': 'designation'},
		{'doctype': 'Contract', 'fieldname': 'party_business_type'},
		{'doctype': 'Contract', 'fieldname': 'signed_by_company_date'},
		{'doctype': 'Purchase Receipt Item', 'fieldname': 'cultivation_tax_details'},
		{'doctype': 'Purchase Receipt Item', 'fieldname': 'flower_weight'},
		{'doctype': 'Purchase Receipt Item', 'fieldname': 'leaf_weight'},
		{'doctype': 'Purchase Receipt Item', 'fieldname': 'plant_weight'},
		{'doctype': 'Purchase Receipt Item', 'fieldname': 'column_break_64'},
		{'doctype': 'Purchase Receipt Item', 'fieldname': 'cultivation_weight_uom'},
		{'doctype': 'User', 'fieldname': 'column_break_2'},
		{'doctype': 'User', 'fieldname': 'works_with_bloomstack'},
		{'doctype': 'Employee', 'fieldname': 'social_security_number'},
		{'doctype': 'Employee', 'fieldname': 'kra'},
		{'doctype': 'Employee', 'fieldname': 'id_verification'},
		{'doctype': 'Employee', 'fieldname': 'background_check'},
		{'doctype': 'Batch', 'fieldname': 'item_group'},
		{'doctype': 'Packing Slip', 'fieldname': 'company'},
		{'doctype': 'Packing Slip', 'fieldname': 'target_warehouse'},
		{'doctype': 'Packing Slip', 'fieldname': 'column_break_12'},
		{'doctype': 'Packing Slip', 'fieldname': 'source_warehouse'},
		{'doctype': 'Packing Slip', 'fieldname': 'section_break_10'},
		{'doctype': 'Timesheet Detail', 'fieldname': 'task_name'},
		{'doctype': 'Sales Order', 'fieldname': 'no_charge_order'},
		{'doctype': 'Sales Order', 'fieldname': 'contract'},
		{'doctype': 'Sales Order', 'fieldname': 'license'},
		{'doctype': 'Sales Order', 'fieldname': 'is_overdue'},
		{'doctype': 'Delivery Settings', 'fieldname': 'delivery_defaults'},
		{'doctype': 'Delivery Settings', 'fieldname': 'packing_warehouse'},
		{'doctype': 'Delivery Settings', 'fieldname': 'default_activity_type'},
		{'doctype': 'Delivery Settings', 'fieldname': 'send_delivery_window_warning'},
		{'doctype': 'Packing Slip Item', 'fieldname': 'target_warehouse'},
		{'doctype': 'Packing Slip Item', 'fieldname': 'column_break_8'},
		{'doctype': 'Packing Slip Item', 'fieldname': 'source_warehouse'},
		{'doctype': 'Packing Slip Item', 'fieldname': 'warehouse_details'},
		{'doctype': 'Work Order', 'fieldname': 'title'},
		{'doctype': 'Purchase Invoice Item', 'fieldname': 'cultivation_tax_details'},
		{'doctype': 'Purchase Invoice Item', 'fieldname': 'flower_weight'},
		{'doctype': 'Purchase Invoice Item', 'fieldname': 'leaf_weight'},
		{'doctype': 'Purchase Invoice Item', 'fieldname': 'cultivation_weight_uom'},
		{'doctype': 'Purchase Invoice Item', 'fieldname': 'column_break_59'},
		{'doctype': 'Purchase Invoice Item', 'fieldname': 'plant_weight'},
		{'doctype': 'Purchase Receipt', 'fieldname': 'license'},
		{'doctype': 'Purchase Receipt', 'fieldname': 'payment_terms'},
		{'doctype': 'Purchase Receipt', 'fieldname': 'payment_terms_template'},
		{'doctype': 'Purchase Receipt', 'fieldname': 'payment_schedule'},
		{'doctype': 'Purchase Receipt', 'fieldname': 'reverse_calculate'},
		{'doctype': 'Project Template Task', 'fieldname': 'billable'},
		{'doctype': 'Purchase Order', 'fieldname': 'license'},
		{'doctype': 'Purchase Order', 'fieldname': 'reverse_calculate'},
		{'doctype': 'Stock Settings', 'fieldname': 'autoname_item'},
		{'doctype': 'Purchase Order Item', 'fieldname': 'cultivation_tax_details'},
		{'doctype': 'Purchase Order Item', 'fieldname': 'flower_weight'},
		{'doctype': 'Purchase Order Item', 'fieldname': 'leaf_weight'},
		{'doctype': 'Purchase Order Item', 'fieldname': 'plant_weight'},
		{'doctype': 'Purchase Order Item', 'fieldname': 'column_break_55'},
		{'doctype': 'Purchase Order Item', 'fieldname': 'cultivation_weight_uom'},
		{'doctype': 'Company', 'fieldname': 'contact_name'},
		{'doctype': 'Company', 'fieldname': 'default_excise_tax_account'},
		{'doctype': 'Company', 'fieldname': 'default_sales_tax_account'},
		{'doctype': 'Company', 'fieldname': 'default_shipping_account'},
		{'doctype': 'Company', 'fieldname': 'licenses'},
		{'doctype': 'Company', 'fieldname': 'licenses_sb'},
		{'doctype': 'Company', 'fieldname': 'default_cultivation_tax_account_leaf'},
		{'doctype': 'Company', 'fieldname': 'default_cultivation_tax_account_flower'},
		{'doctype': 'Company', 'fieldname': 'default_cultivation_tax_account_plant'},
		{'doctype': 'Company', 'fieldname': 'section_break_56'},
		{'doctype': 'Company', 'fieldname': 'column_break_59'},
		{'doctype': 'Driver', 'fieldname': 'user_id'},
		{'doctype': 'Timesheet', 'fieldname': 'delivery_trip'},
		{'doctype': 'Stock Entry Detail', 'fieldname': 'customer'},
		{'doctype': 'Stock Entry Detail', 'fieldname': 'supplier'},
		{'doctype': 'Stock Entry Detail', 'fieldname': 'section_break'},
		{'doctype': 'Stock Entry Detail', 'fieldname': 'column_break'},
		{'doctype': 'Quotation', 'fieldname': 'customer_signature'},
		{'doctype': 'Quotation', 'fieldname': 'signature'},
		{'doctype': 'Quotation', 'fieldname': 'no_charge_order'},
		{'doctype': 'Quotation', 'fieldname': 'license'},
		{'doctype': 'Customer', 'fieldname': 'opening_date'},
		{'doctype': 'Customer', 'fieldname': 'licenses'},
		{'doctype': 'Customer', 'fieldname': 'licenses_sb'},
		{'doctype': 'Package Tag', 'fieldname': 'sb_metrc'},
		{'doctype': 'Package Tag', 'fieldname': 'metrc_stock_qty'},
		{'doctype': 'Package Tag', 'fieldname': 'cb_metrc'},
		{'doctype': 'Package Tag', 'fieldname': 'metrc_stock_uom'},
		{'doctype': 'Package Tag', 'fieldname': 'metrc_product_name'},
		{'doctype': 'Pick List Item', 'fieldname': 'so_customer'},
		{'doctype': 'Pick List Item', 'fieldname': 'cb_reference'},
		{'doctype': 'Purchase Invoice', 'fieldname': 'license'},
		{'doctype': 'Purchase Invoice', 'fieldname': 'reverse_calculate'},
		{'doctype': 'Sales Order Item', 'fieldname': 'batch_no'},
		{'doctype': 'Lead', 'fieldname': 'hub_sync_id'},
		{'doctype': 'Lead', 'fieldname': 'number_of_employees'},
		{'doctype': 'Lead', 'fieldname': 'account_opened_date'},
		{'doctype': 'Lead', 'fieldname': 'region'},
		{'doctype': 'Lead', 'fieldname': 'lead_dashboard'},
		{'doctype': 'Lead', 'fieldname': 'lead_dashboard_cb'},
		{'doctype': 'Lead', 'fieldname': 'type_of_business'},
		{'doctype': 'Warehouse', 'fieldname': 'customer'},
		{'doctype': 'Warehouse', 'fieldname': 'supplier'},
		{'doctype': 'Warehouse', 'fieldname': 'warehouse_party_details'},
		{'doctype': 'Warehouse', 'fieldname': 'column_break'},
		{'doctype': 'Sales Invoice', 'fieldname': 'license'},
		{'doctype': 'Supplier', 'fieldname': 'irs_1099'},
		{'doctype': 'Supplier', 'fieldname': 'licenses'},
		{'doctype': 'Supplier', 'fieldname': 'licenses_sb'}
	]

	doctypes = ['Batch', 'Company', 'Contract', 'Customer', 'Delivery Settings', 'Driver', 'Employee', 'Item', 'Lead', 'Package Tag', 'Packing Slip',
		'Packing Slip Item', 'Payment Schedule', 'Pick List Item', 'Project Template Task', 'Purchase Invoice', 'Purchase Invoice Item', 'Purchase Order',
		'Purchase Order Item', 'Purchase Receipt', 'Purchase Receipt Item', 'Quotation', 'Sales Invoice', 'Sales Order', 'Sales Order Item',
		'Stock Entry Detail', 'Stock Settings', 'Supplier', 'Supplier Quotation', 'Timesheet', 'Timesheet Detail', 'User', 'Warehouse', 'Work Order']


	for field in custom_fields:
		frappe.delete_doc_if_exists("Custom Field", field.get("doctype") + "-" + field.get("fieldname"))

	for doctype in doctypes:
		frappe.reload_doctype(doctype, True)